---
trigger:
  - main
resources:
  - repo: self
variables:
  tag: $(Build.BuildId)
stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: Default
        steps:

          - task: Maven@3
            inputs:
              mavenVersionOption: Default
              mavenPomFile: pom.xml
              options: ""
              goals: clean install
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
              javaHomeOption: JDKVersion
              mavenVersion: 3.8.1
              mavenSetM2Home: true
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: $(Build.SourcesDirectory)/ch09/course-tracker-app-dockerfile/Dockerfile
              tags: |
                $(tag)
