apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-11-10T10:02:46Z"
  generation: 1
  labels:
    app: splunk
  name: course-tracker-deployement
  namespace: demons

spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
        - image: sprasanna1992/spring-boot:b25aaefca9165b532fe2d5898fdb4e6653847ad1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: splunk-config
          name: course-tracker
          ports:
            - containerPort: 8080
#          resources:
#           limits:
#              memory: "128Mi"
#              cpu: "500m"
#           requests:
#             memory: "64Mi"
#             cpu: "250m"
