apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of resources to be included
resources:
  - deployement.yaml
  - exposesplunk.yaml
  - configmap.yaml
  - namespace.yaml
  - splunk-ds-host.yaml
  

# Common labels to be added to all resources
commonLabels:
  app: splunk
