apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-boot-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: kubernetes/overlays/dev
    repoURL: https://github.com/Sivaneni/spring-boot1.git
    targetRevision: HEAD
    kustomize:
      images: []
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
