apiVersion: v1
kind: Service
metadata:
  name: splunk
  labels:
    app: splunk
  namespace: demons
spec:
  selector:
    app: splunk
  ports:
    - name: http-splunk
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: web-splunk
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: course-tracker
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
