---
name: Spring Boot in Practice CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          
          - ch09/course-tracker-app-dockerfile
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "17"
      - name: Assemble and test
        run: |
          cd ${{ matrix.project }}
          chmod +x mvnw
          ./mvnw clean install
      - name: Copy JAR file
        run: >
          mkdir -p ch09/course-tracker-app-dockerfile/target

          cp ${{ matrix.project }}/target/*.jar ch09/course-tracker-app-dockerfile/target/
