---
name: Spring Boot in Practice CI to dockerhub
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - ch09/course-tracker-app-dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: "17"
      - name: Assemble and test
        run: |
          cd ${{ matrix.project }}
          chmod +x mvnw
          ./mvnw clean install
      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: ${{ matrix.project }}/target/*.jar
      - name: setup docker
        uses: docker/setup-buildx-action@v3
      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.project }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot:${{ github.sha }}
