name: my  first workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo"sample run"
        
        - name: list files
          run: ls