name: my  first workflow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "sample run"
        - name: git checkout repo
          uses: actions/checkout@v4
        
        - name: list files
          run: |  
                ls -ltra
                cat README.md
                
        - name: generate ASCII artwork
          run: |
            chmod +x ascii_script.sh
            ./Sivaneni/spring-boot1/.github/workflows/ascii_script.sh
        